.PHONY : all
all : stack_allocation heap_allocation reducing_memory_fragmentation writing_to_files reading_from_files

stack_allocation : stack_allocation.c
	gcc -o stack_allocation stack_allocation.c

heap_allocation : heap_allocation.c
	gcc -o heap_allocation heap_allocation.c

reducing_memory_fragmentation : reducing_memory_fragmentation.c
	gcc -o reducing_memory_fragmentation reducing_memory_fragmentation.c

writing_to_files : writing_to_files.c
	gcc -o writing_to_files writing_to_files.c

reading_from_files : reading_from_files.c
	gcc -o reading_from_files reading_from_files.c