.PHONY : all
all : what_is_memory_sizeof what_is_memory_allocate arrays_run allocation

what_is_memory_sizeof : what_is_memory_sizeof.c
	gcc -o what_is_memory_sizeof what_is_memory_sizeof.c

what_is_memory_allocate : what_is_memory_allocate.c
	gcc -o what_is_memory_allocate what_is_memory_allocate.c

arrays_run : arrays.c
	gcc -o arrays_run arrays.c

allocation : allocation.c
	gcc -o allocation allocation.c